<a href="https://colab.research.google.com/github/lateefurrahman/AI-Q1-learning-resources/blob/master/08_06_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
samples = ['Congratulate Bilal Ahmed and 5 others for work anniversaries.', 'You appeared in 1 search this week.','Lateef heres the news professionals are talking about now curated by LinkedIns editors.','Marketing Communications Consultant You and Faysal have 226 mutual connections in common']


In [35]:
token_index = {}
for sample in samples:
    for word in sample.split():
        if word not in token_index:
            token_index[word] = len(token_index) + 1
token_index            


{'1': 13,
 '226': 35,
 '5': 5,
 'Ahmed': 3,
 'Bilal': 2,
 'Communications': 31,
 'Congratulate': 1,
 'Consultant': 32,
 'Faysal': 33,
 'Lateef': 17,
 'LinkedIns': 28,
 'Marketing': 30,
 'You': 10,
 'about': 24,
 'and': 4,
 'anniversaries.': 9,
 'appeared': 11,
 'are': 22,
 'by': 27,
 'common': 38,
 'connections': 37,
 'curated': 26,
 'editors.': 29,
 'for': 7,
 'have': 34,
 'heres': 18,
 'in': 12,
 'mutual': 36,
 'news': 20,
 'now': 25,
 'others': 6,
 'professionals': 21,
 'search': 14,
 'talking': 23,
 'the': 19,
 'this': 15,
 'week.': 16,
 'work': 8}

In [36]:
max_length = 10
results = np.zeros(shape=(len(samples),max_length,max(token_index.values()) + 1))
results

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

In [37]:
for i, sample in enumerate(samples):
    for j, word in list(enumerate(sample.split()))[:max_length]:
        index = token_index.get(word)
        results[i, j, index] = 1.

index

37

In [0]:
import string

In [0]:
samples = ['The cat sat on the mat.', 'The dog ate my homework.']


In [41]:
characters = string.printable
token_index = dict(zip(range(1, len(characters) + 1), characters))
characters
token_index

{1: '0',
 2: '1',
 3: '2',
 4: '3',
 5: '4',
 6: '5',
 7: '6',
 8: '7',
 9: '8',
 10: '9',
 11: 'a',
 12: 'b',
 13: 'c',
 14: 'd',
 15: 'e',
 16: 'f',
 17: 'g',
 18: 'h',
 19: 'i',
 20: 'j',
 21: 'k',
 22: 'l',
 23: 'm',
 24: 'n',
 25: 'o',
 26: 'p',
 27: 'q',
 28: 'r',
 29: 's',
 30: 't',
 31: 'u',
 32: 'v',
 33: 'w',
 34: 'x',
 35: 'y',
 36: 'z',
 37: 'A',
 38: 'B',
 39: 'C',
 40: 'D',
 41: 'E',
 42: 'F',
 43: 'G',
 44: 'H',
 45: 'I',
 46: 'J',
 47: 'K',
 48: 'L',
 49: 'M',
 50: 'N',
 51: 'O',
 52: 'P',
 53: 'Q',
 54: 'R',
 55: 'S',
 56: 'T',
 57: 'U',
 58: 'V',
 59: 'W',
 60: 'X',
 61: 'Y',
 62: 'Z',
 63: '!',
 64: '"',
 65: '#',
 66: '$',
 67: '%',
 68: '&',
 69: "'",
 70: '(',
 71: ')',
 72: '*',
 73: '+',
 74: ',',
 75: '-',
 76: '.',
 77: '/',
 78: ':',
 79: ';',
 80: '<',
 81: '=',
 82: '>',
 83: '?',
 84: '@',
 85: '[',
 86: '\\',
 87: ']',
 88: '^',
 89: '_',
 90: '`',
 91: '{',
 92: '|',
 93: '}',
 94: '~',
 95: ' ',
 96: '\t',
 97: '\n',
 98: '\r',
 99: '\x0b',
 100: '\x0c'

In [42]:
max_length = 50
results = np.zeros((len(samples), max_length, max(token_index.keys()) + 1))
for i, sample in enumerate(samples):
    for j, character in enumerate(sample):
        index = token_index.get(character)
        results[i, j, index] = 1.

results        

array([[[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

In [0]:
from tensorflow.keras.preprocessing.text import Tokenizer


In [0]:
samples = ['Congratulate Bilal Ahmed and 5 others for work anniversaries.', 'You appeared in 1 search this week.','Lateef heres the news professionals are talking about now curated by LinkedIns editors.','Marketing Communications Consultant You and Faysal have 226 mutual connections in common']


In [46]:
tokenizer = Tokenizer(num_words=1000)
tokenizer.fit_on_texts(samples)
print(tokenizer)

In [48]:
sequences = tokenizer.texts_to_sequences(samples)
print(sequences)

[[4, 5, 6, 1, 7, 8, 9, 10, 11], [2, 12, 3, 13, 14, 15, 16], [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], [30, 31, 32, 2, 1, 33, 34, 35, 36, 37, 3, 38]]


In [49]:
one_hot_results = tokenizer.texts_to_matrix(samples, mode='binary')
one_hot_results

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.]])

In [51]:
word_index = tokenizer.word_index
print('Found %s unique tokens.' % len(word_index))


Found 38 unique tokens.


In [52]:
word_index

{'1': 13,
 '226': 35,
 '5': 7,
 'about': 24,
 'ahmed': 6,
 'and': 1,
 'anniversaries': 11,
 'appeared': 12,
 'are': 22,
 'bilal': 5,
 'by': 27,
 'common': 38,
 'communications': 31,
 'congratulate': 4,
 'connections': 37,
 'consultant': 32,
 'curated': 26,
 'editors': 29,
 'faysal': 33,
 'for': 9,
 'have': 34,
 'heres': 18,
 'in': 3,
 'lateef': 17,
 'linkedins': 28,
 'marketing': 30,
 'mutual': 36,
 'news': 20,
 'now': 25,
 'others': 8,
 'professionals': 21,
 'search': 14,
 'talking': 23,
 'the': 19,
 'this': 15,
 'week': 16,
 'work': 10,
 'you': 2}

In [59]:
samples = ['Congratulate Bilal Ahmed and 5 others for work anniversaries.', 'You appeared in 1 search this week.','Lateef heres the news professionals are talking about now curated by LinkedIns editors.','Marketing Communications Consultant You and Faysal have 226 mutual connections in common','We want to give you a boost Heres one month of LinkedIn Premium for free.']
samples

['Congratulate Bilal Ahmed and 5 others for work anniversaries.',
 'You appeared in 1 search this week.',
 'Lateef heres the news professionals are talking about now curated by LinkedIns editors.',
 'Marketing Communications Consultant You and Faysal have 226 mutual connections in common',
 'We want to give you a boost Heres one month of LinkedIn Premium for free.']

In [0]:
dimensionality = 1000
max_length = 10


In [0]:
results = np.zeros((len(samples), max_length, dimensionality))
for i, sample in enumerate(samples):
    for j, word in list(enumerate(sample.split()))[:max_length]:
        index = abs(hash(word)) % dimensionality
        results[i, j, index] = 1.

In [63]:
print(results ,index)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]] 537
